import jsPDF from 'jspdf';

interface TeamMember {
  id: number;
  name: string;
  speciality: string;
  hoursPerDay: number;
}

interface Project {
  task: string;
  createdAt: string;
}

interface TeamAllocation {
  project: Project;
  teamMembers: TeamMember[];
  totalMembers: number;
  totalHoursPerDay: number;
}

interface ApiResponse {
  error?: string;
  success?: boolean;
}

export async function POST(request: Request): Promise<Response> {
  try {
    const teamData: TeamAllocation = await request.json()
    
    if (!teamData || !teamData.project || !teamData.teamMembers || !Array.isArray(teamData.teamMembers)) {
      return Response.json({ error: 'Invalid team data structure' } as ApiResponse, {
        status: 400,
      });
    }
    
    if (teamData.teamMembers.length === 0) {
      return Response.json({ error: 'No team members provided' } as ApiResponse, {
        status: 400,
      });
    }

    const doc = new jsPDF();
    const primaryColor = '#e26e47';
    const textColor = '#2b2b28';
    doc.setFontSize(28);
    doc.setTextColor(primaryColor);
    doc.text('Team Allocation Report', 20, 25);
    
    doc.setFontSize(16);
    doc.setTextColor(textColor);
    doc.text('Generated by Allocatr', 20, 35);
    
    doc.setFontSize(10);
    doc.setTextColor('#666666');
    const createdDate = new Date(teamData.project.createdAt).toLocaleDateString();
    doc.text(`Created: ${createdDate}`, 20, 45);
    doc.setFontSize(16);
    doc.setTextColor(primaryColor);
    doc.text('Project Details', 20, 60);
    
    doc.setFontSize(12);
    doc.setTextColor(textColor);
    doc.text('Task Description:', 20, 70);
    const taskText: string = teamData.project.task || 'No task description provided';
    const splitTask = doc.splitTextToSize(taskText, 170);
    doc.text(splitTask, 20, 80);

    let currentY: number = 80 + (Array.isArray(splitTask) ? splitTask.length * 5 : 5) + 10;
    doc.setFontSize(16);
    doc.setTextColor(primaryColor);
    doc.text('Project Summary', 20, currentY);
    currentY += 15;
    
    doc.setFontSize(12);
    doc.setTextColor(textColor);
    doc.text(`Total Team Members: ${teamData.totalMembers}`, 20, currentY);
    currentY += 8;
    doc.text(`Total Hours per Day: ${teamData.totalHoursPerDay}`, 20, currentY);
    currentY += 20;
    doc.setFontSize(16);
    doc.setTextColor(primaryColor);
    doc.text('Team Members', 20, currentY);
    currentY += 15;
    doc.setFontSize(12);
    doc.setTextColor(textColor);

    doc.setFont(undefined, 'bold');
    doc.text('ID', 20, currentY);
    doc.text('Name', 40, currentY);
    doc.text('Speciality', 100, currentY);
    doc.text('Hours/Day', 160, currentY);
    currentY += 5;
    doc.line(20, currentY, 190, currentY);
    currentY += 10;
    doc.setFont(undefined, 'normal');
    teamData.teamMembers.forEach((member: TeamMember) => {
      if (currentY > 270) {
        doc.addPage();
        currentY = 20;
      }
      
      doc.text(member.id.toString(), 20, currentY);
      doc.text(member.name || 'N/A', 40, currentY);
      doc.text(member.speciality || 'N/A', 100, currentY);
      doc.text(member.hoursPerDay.toString(), 160, currentY);
      currentY += 10;
    });

    const pageCount = (doc as any).getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor('#999999');
      doc.text(
        `Page ${i} of ${pageCount} | Generated by Allocatr`,
        20,
        (doc as any).internal.pageSize.height - 10
      );
    }

    const pdfBuffer: ArrayBuffer = doc.output('arraybuffer');

    return new Response(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="team-allocation-${Date.now()}.pdf"`
      }
    });
    
  } catch (error: unknown) {
    console.error('Error generating PDF:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    
    return Response.json({ error: `Failed to generate PDF: ${errorMessage}` } as ApiResponse, {
      status: 500,
    });
  }
}